package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"auto-bughunter/backend/internal/model"
)

type Client struct {
	BaseURL string
	APIKey  string
	Model   string
	// Optional larger coding-focused model for orchestration/planning calls.
	CodingBaseURL string
	CodingAPIKey  string
	CodingModel   string
	HTTP    *http.Client
}

func NewClient(baseURL, apiKey, model string) *Client {
	if baseURL == "" {
		baseURL = "https://api.openai.com/v1"
	}
	if model == "" {
		model = "gpt-4o-mini"
	}
	return &Client{
		BaseURL: strings.TrimRight(baseURL, "/"),
		APIKey:  apiKey,
		Model:   model,
		HTTP:    &http.Client{Timeout: 20 * time.Second},
	}
}

func (c *Client) ConfigureCodingModel(baseURL, apiKey, model string) {
	if c == nil {
		return
	}
	model = strings.TrimSpace(model)
	if model == "" {
		c.CodingBaseURL = ""
		c.CodingAPIKey = ""
		c.CodingModel = ""
		return
	}

	baseURL = strings.TrimSpace(baseURL)
	if baseURL == "" {
		baseURL = c.BaseURL
	}
	apiKey = strings.TrimSpace(apiKey)
	if apiKey == "" {
		apiKey = c.APIKey
	}

	c.CodingBaseURL = strings.TrimRight(baseURL, "/")
	c.CodingAPIKey = apiKey
	c.CodingModel = model
}

func (c *Client) Summarize(ctx context.Context, target string, findings []model.Finding) string {
	return c.SummarizeWithKnowledge(ctx, target, findings, nil)
}

func (c *Client) SummarizeWithKnowledge(ctx context.Context, target string, findings []model.Finding, knowledge *model.SecurityKnowledgeContext) string {
	if !c.shouldCallProvider() {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}

	payload := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{
				"role":    "system",
				"content": "You are a defensive AppSec assistant. Summarize scanner findings for authorized remediation only. Use supplied curated references as supporting context, and preserve citations as source titles plus URLs.",
			},
			{
				"role":    "user",
				"content": fmt.Sprintf("Target: %s\nFindings JSON: %s\nKnowledge Context JSON: %s\nProvide: 1) risk summary 2) top 3 priorities 3) remediation sequence 4) supporting citations when knowledge context is present.", target, mustJSON(findings), mustJSON(knowledge)),
			},
		},
		"temperature": 0.2,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.BaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	if strings.TrimSpace(c.APIKey) != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}

	var out struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	if len(out.Choices) == 0 || strings.TrimSpace(out.Choices[0].Message.Content) == "" {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	return out.Choices[0].Message.Content
}

func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "[]"
	}
	return string(b)
}

// VulnerabilityHypothesis is a single testable vulnerability hypothesis
// generated by the AI provider and intended for deterministic scanner
// verification. The scanner executes a targeted probe based on the
// category/endpoint/payload hint and only surfaces a finding when the
// oracle confirms the vulnerability.
type VulnerabilityHypothesis struct {
	ID          string `json:"id"`
	Endpoint    string `json:"endpoint"`
	Method      string `json:"method"`
	ParamName   string `json:"paramName,omitempty"`
	PayloadHint string `json:"payloadHint"`
	Category    string `json:"category"`
	Rationale   string `json:"rationale"`
}

// Hypothesize asks the configured AI provider to generate testable
// vulnerability hypotheses for the given target given the current finding
// set and known surface endpoints. Each hypothesis describes a specific
// probe (endpoint, parameter, payload) that the scanner verifies with a
// deterministic oracle. Only scanner-confirmed hypotheses are surfaced as
// findings, preventing hallucinated reports.
//
// Falls back to a rule-based local reasoner when no AI provider is configured.
func (c *Client) Hypothesize(ctx context.Context, target string, findings []model.Finding, endpoints []string) []VulnerabilityHypothesis {
	if c == nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if !c.shouldCallProvider() {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	type hypothesisRequest struct {
		Target       string          `json:"target"`
		Findings     []model.Finding `json:"findings"`
		Endpoints    []string        `json:"endpoints"`
		Instructions string          `json:"instructions"`
	}
	hreq := hypothesisRequest{
		Target:    target,
		Findings:  findings,
		Endpoints: endpoints,
		Instructions: "Generate up to 5 testable vulnerability hypotheses. For each, specify: " +
			"a concrete endpoint URL, HTTP method (GET/POST), optional parameter name, " +
			"a payload hint (e.g. \"' OR 1=1 --\", \"<script>\", \"/../etc/passwd\"), " +
			"category (one of: sqli|xss|open_redirect|ssrf|cors|auth_bypass|idor|ssti|business_logic), " +
			"and a rationale. Only propose hypotheses verifiable by a deterministic scanner oracle. " +
			"Reply with strict JSON only: " +
			"{\"hypotheses\":[{\"id\":string,\"endpoint\":string,\"method\":string,\"paramName\":string,\"payloadHint\":string,\"category\":string,\"rationale\":string}]}",
	}
	userJSON, err := json.Marshal(hreq)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	payload := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{
				"role":    "system",
				"content": "You are an autonomous security researcher generating testable vulnerability hypotheses. Reply with strict JSON.",
			},
			{
				"role":    "user",
				"content": string(userJSON),
			},
		},
		"temperature":     0.3,
		"response_format": map[string]string{"type": "json_object"},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.BaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if strings.TrimSpace(c.APIKey) != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if len(apiResp.Choices) == 0 {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	content := stripCodeFence(strings.TrimSpace(apiResp.Choices[0].Message.Content))
	if content == "" {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	var parsed struct {
		Hypotheses []VulnerabilityHypothesis `json:"hypotheses"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	return parsed.Hypotheses
}

func (c *Client) shouldCallProvider() bool {
	return shouldCallProviderFor(c.BaseURL, c.APIKey)
}

func (c *Client) planningProvider() (baseURL, apiKey, model string) {
	baseURL = c.BaseURL
	apiKey = c.APIKey
	model = c.Model

	if strings.TrimSpace(c.CodingModel) == "" {
		return baseURL, apiKey, model
	}
	if shouldCallProviderFor(c.CodingBaseURL, c.CodingAPIKey) {
		return c.CodingBaseURL, c.CodingAPIKey, c.CodingModel
	}
	return baseURL, apiKey, model
}

func shouldCallProviderFor(baseURL, apiKey string) bool {
	// Keep OpenAI default behavior: require an API key.
	const defaultOpenAIBase = "https://api.openai.com/v1"
	base := strings.TrimRight(strings.ToLower(strings.TrimSpace(baseURL)), "/")
	if strings.TrimSpace(apiKey) != "" {
		return true
	}
	return base != strings.ToLower(defaultOpenAIBase)
}

// GeneratedToolSpec is the Python tool source returned by the coding LLM.
// It mirrors toolbuilder.ToolSpec but is defined here to avoid a circular
// import — the toolbuilder package imports ai indirectly through the agent
// layer.
type GeneratedToolSpec struct {
	// Name is a short identifier used as the script filename (no extension).
	Name string
	// Code is the full Python 3 script source. The script must accept a
	// target URL as its first positional argument and write JSON-lines
	// findings to stdout.
	Code string
	// Rationale is the LLM's explanation for why this tool was chosen.
	Rationale string
}

// GenerateTool asks the configured coding LLM to write a Python 3 pen testing
// tool for the described task on the given target. The script must:
//   - accept a target URL as sys.argv[1]
//   - output zero or more JSON-lines findings to stdout, each with keys:
//     id, category, severity, title, description, evidence, recommendation
//   - use only the Python 3 standard library (no third-party packages)
//   - contain no subprocess, os.system, eval, exec, or raw socket calls
//
// Falls back to a nil result (no code generated) when the coding LLM is not
// configured or the request fails, allowing callers to gracefully skip
// AI-generated tooling.
func (c *Client) GenerateTool(ctx context.Context, taskDescription string, target string, contextFindings []string) *GeneratedToolSpec {
	if c == nil {
		return nil
	}
	baseURL, apiKey, model := c.planningProvider()
	if !shouldCallProviderFor(baseURL, apiKey) {
		return nil
	}

	systemPrompt := "You are an expert Python 3 security tool developer. " +
		"Write a concise, self-contained Python 3 pen testing script. " +
		"Rules: accept target URL as sys.argv[1]; print zero or more " +
		"JSON-lines findings to stdout, each with keys id, category, severity, " +
		"title, description, evidence, recommendation; use only the Python 3 " +
		"standard library (urllib, json, sys, re, base64, hashlib, hmac, ssl, " +
		"socket — but no subprocess, os.system, eval, exec, or raw socket.connect). " +
		"Output strict JSON only: {\"name\":string,\"code\":string,\"rationale\":string}"

	userPayload := map[string]any{
		"task":             taskDescription,
		"target":           target,
		"context_findings": contextFindings,
	}
	userJSON, err := json.Marshal(userPayload)
	if err != nil {
		return nil
	}

	payload := map[string]any{
		"model": model,
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": string(userJSON)},
		},
		"temperature":     0.2,
		"response_format": map[string]string{"type": "json_object"},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return nil
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return nil
	}
	if strings.TrimSpace(apiKey) != "" {
		req.Header.Set("Authorization", "Bearer "+apiKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return nil
	}

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil
	}
	if len(apiResp.Choices) == 0 {
		return nil
	}
	content := stripCodeFence(strings.TrimSpace(apiResp.Choices[0].Message.Content))
	if content == "" {
		return nil
	}

	var parsed struct {
		Name      string `json:"name"`
		Code      string `json:"code"`
		Rationale string `json:"rationale"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return nil
	}
	name := strings.TrimSpace(parsed.Name)
	code := strings.TrimSpace(parsed.Code)
	if name == "" || code == "" {
		return nil
	}
	return &GeneratedToolSpec{
		Name:      name,
		Code:      code,
		Rationale: strings.TrimSpace(parsed.Rationale),
	}
}

// AdaptedCommand is a single concrete command that the coding LLM has adapted
// from a HackTricks command template to the specific finding and target.
type AdaptedCommand struct {
	Binary    string   `json:"binary"`
	Args      []string `json:"args"`
	Rationale string   `json:"rationale"`
}

// AdaptTechniqueCommands asks the coding LLM to fill in the {{TARGET}},
// {{HOST}}, {{PATH}}, and {{PARAM}} placeholders in each template string with
// values extracted from the finding evidence and target URL.  The LLM may also
// augment the commands (e.g. tightening sqlmap flags based on DBMS hints in
// the evidence, or adding the correct cookie header when credentials are known).
//
// Each element of templates should be the human-readable form of one command
// invocation, e.g. "sqlmap -u {{TARGET}}?{{PARAM}}=1 --batch".
//
// Returns nil when the coding LLM is not configured or the request fails;
// callers should fall back to simple string substitution in that case.
func (c *Client) AdaptTechniqueCommands(ctx context.Context, templates []string, findingTitle, findingEvidence, target string) []AdaptedCommand {
	if c == nil {
		return nil
	}
	baseURL, apiKey, model := c.planningProvider()
	if !shouldCallProviderFor(baseURL, apiKey) {
		return nil
	}

	systemPrompt := "You are an expert penetration tester. " +
		"You receive a list of HackTricks command templates with placeholders " +
		"({{TARGET}}, {{HOST}}, {{PATH}}, {{PARAM}}) and a finding with its evidence. " +
		"For each template, produce a concrete, ready-to-run command adapted to the actual target and finding. " +
		"Rules: " +
		"(1) Replace {{TARGET}} with the exact target URL. " +
		"(2) Replace {{HOST}} with the target hostname. " +
		"(3) Replace {{PATH}} with the relevant path extracted from the evidence, or / if unknown. " +
		"(4) Replace {{PARAM}} with the vulnerable parameter name from the evidence, or 'id' if unknown. " +
		"(5) Only use binaries from this list: sqlmap curl dalfox gobuster ffuf nikto nmap nuclei subfinder httpx python3 wafw00f wpscan arjun. " +
		// NOTE: this list mirrors cmdbuilder.allowedBinaries. If that list
		// changes, update here too so the LLM prompt stays in sync.
		"(6) Do NOT add shell operators (&&, ||, ;, |, $(), backticks, or redirects). " +
		"(7) Output strict JSON only: {\"commands\":[{\"binary\":string,\"args\":[string,...],\"rationale\":string}]}"

	type adaptRequest struct {
		Target          string   `json:"target"`
		FindingTitle    string   `json:"finding_title"`
		FindingEvidence string   `json:"finding_evidence"`
		Templates       []string `json:"templates"`
	}
	reqBody := adaptRequest{
		Target:          target,
		FindingTitle:    findingTitle,
		FindingEvidence: findingEvidence,
		Templates:       templates,
	}
	userJSON, err := json.Marshal(reqBody)
	if err != nil {
		return nil
	}

	payload := map[string]any{
		"model": model,
		"messages": []map[string]string{
			{"role": "system", "content": systemPrompt},
			{"role": "user", "content": string(userJSON)},
		},
		"temperature":     0.1,
		"response_format": map[string]string{"type": "json_object"},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return nil
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return nil
	}
	if strings.TrimSpace(apiKey) != "" {
		req.Header.Set("Authorization", "Bearer "+apiKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return nil
	}

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil
	}
	if len(apiResp.Choices) == 0 {
		return nil
	}
	content := stripCodeFence(strings.TrimSpace(apiResp.Choices[0].Message.Content))
	if content == "" {
		return nil
	}

	var parsed struct {
		Commands []AdaptedCommand `json:"commands"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return nil
	}
	out := make([]AdaptedCommand, 0, len(parsed.Commands))
	for _, cmd := range parsed.Commands {
		if strings.TrimSpace(cmd.Binary) != "" && len(cmd.Args) > 0 {
			out = append(out, cmd)
		}
	}
	return out
}

// SynthesizedChain is a novel multi-step attack chain proposed by the LLM.
type SynthesizedChain struct {
	// ID is a short machine-readable label (e.g. "jwt-cors-token-theft").
	ID string `json:"id"`
	// Title is the one-line chain description.
	Title string `json:"title"`
	// Steps is the ordered list of exploitation steps.
	Steps []string `json:"steps"`
	// Impact is a one-sentence description of the attacker's gain.
	Impact string `json:"impact"`
	// SourceIDs lists the Finding IDs that triggered this chain.
	SourceIDs []string `json:"sourceIds,omitempty"`
	// Confidence is the model's self-assessed confidence in 0.0–1.0.
	Confidence float64 `json:"confidence"`
}

// SynthesizeChains sends the full finding set to the AI and asks it to reason
// about novel multi-step attack chains that the static rules do not cover.
// Results are filtered to only include chains with Confidence >= 0.60 so
// low-quality hallucinations are suppressed before they become findings.
//
// Falls back to nil when no AI provider is configured.
func (c *Client) SynthesizeChains(ctx context.Context, target string, findingSet []map[string]string) []SynthesizedChain {
	if c == nil {
		return nil
	}
	baseURL, apiKey, model := c.planningProvider()
	if !shouldCallProviderFor(baseURL, apiKey) {
		return nil
	}
	if len(findingSet) == 0 {
		return nil
	}

	userPayload := map[string]any{
		"target":      target,
		"findings":    findingSet,
		"instructions": "You are an elite penetration tester. Analyse the provided finding set and reason about " +
			"novel multi-step attack chains NOT already represented in the findings. " +
			"Focus on chaining 2–4 findings together to achieve a higher-impact outcome than any individual finding. " +
			"For each chain: assign a short machine-readable id, a one-line title, ordered exploitation steps (3–6), " +
			"a one-sentence impact statement, list the source finding IDs involved, and a confidence score (0.0–1.0). " +
			"Reply with strict JSON only: " +
			`{"chains":[{"id":string,"title":string,"steps":[string],"impact":string,"sourceIds":[string],"confidence":number}]}`,
	}
	userJSON, err := json.Marshal(userPayload)
	if err != nil {
		return nil
	}

	payload := map[string]any{
		"model": model,
		"messages": []map[string]string{
			{
				"role":    "system",
				"content": "You are an expert penetration tester generating multi-step exploit chains. Reply with strict JSON.",
			},
			{
				"role":    "user",
				"content": string(userJSON),
			},
		},
		"temperature":     0.3,
		"response_format": map[string]string{"type": "json_object"},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return nil
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, baseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return nil
	}
	if strings.TrimSpace(apiKey) != "" {
		req.Header.Set("Authorization", "Bearer "+apiKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return nil
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return nil
	}

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil
	}
	if len(apiResp.Choices) == 0 {
		return nil
	}
	content := stripCodeFence(strings.TrimSpace(apiResp.Choices[0].Message.Content))
	if content == "" {
		return nil
	}

	var parsed struct {
		Chains []SynthesizedChain `json:"chains"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return nil
	}

	out := make([]SynthesizedChain, 0, len(parsed.Chains))
	for _, ch := range parsed.Chains {
		if strings.TrimSpace(ch.ID) == "" || strings.TrimSpace(ch.Title) == "" {
			continue
		}
		if ch.Confidence < 0.60 {
			continue
		}
		out = append(out, ch)
	}
	return out
}

// DomainProfilePack contains domain-specific instructions injected into the AI
// planner's system prompt to tune its decisions to the target's business context.
type DomainProfilePack struct {
	// Name identifies the pack (e.g. "fintech", "healthcare").
	Name string
	// HostPatterns are domain suffix patterns that trigger this pack.
	HostPatterns []string
	// PriorityAreas are the highest-value vulnerability classes for this domain.
	PriorityAreas []string
	// SystemInstruction is injected into the AI planner's system message.
	SystemInstruction string
}

// domainProfilePacks maps known domain profiles to contextual AI instructions.
var domainProfilePacks = []DomainProfilePack{
	{
		Name:         "fintech",
		HostPatterns: []string{"pay", "bank", "finance", "wallet", "money", "transfer", "trade", "invest", "loan", "credit", "fintech"},
		PriorityAreas: []string{
			"payment flow manipulation",
			"price and quantity parameter tampering",
			"race conditions on transaction endpoints",
			"account balance manipulation",
			"double-spend attacks",
		},
		SystemInstruction: "This is a FINTECH target. Prioritize: (1) payment and transfer flow integrity " +
			"(race conditions, double-spend, negative amounts); (2) price manipulation in cart/checkout; " +
			"(3) authorization bypass on account balance and transaction history; " +
			"(4) PCI-DSS relevant findings (card data exposure, unencrypted storage, weak TLS). " +
			"Frame risk rationale using PCI-DSS impact. Elevate any finding that could cause financial loss.",
	},
	{
		Name:         "healthcare",
		HostPatterns: []string{"health", "medical", "clinic", "hospital", "patient", "ehr", "emr", "pharmacy", "prescription", "hipaa"},
		PriorityAreas: []string{
			"PHI/PII exposure",
			"IDOR on patient records",
			"authentication bypass",
			"audit log tampering",
		},
		SystemInstruction: "This is a HEALTHCARE target. Prioritize: (1) PHI exposure (HIPAA-relevant findings); " +
			"(2) IDOR on patient records and appointments; (3) authentication bypass on clinician accounts; " +
			"(4) audit log integrity (can findings be covered up?). " +
			"Frame risk rationale using HIPAA/HITECH impact. Elevation to high when PHI is in scope.",
	},
	{
		Name:         "saas",
		HostPatterns: []string{"app.", "dashboard", "portal", "platform", "cloud", "saas"},
		PriorityAreas: []string{
			"tenant isolation",
			"IDOR across accounts",
			"privilege escalation within roles",
			"API key / secret leakage",
		},
		SystemInstruction: "This is a SaaS/multi-tenant target. Prioritize: (1) cross-tenant IDOR (can a tenant A access tenant B data?); " +
			"(2) privilege escalation within a tenant (viewer → admin); (3) API key enumeration and weak token generation; " +
			"(4) secrets in JS bundles. Frame risk using SLA and data isolation impact.",
	},
	{
		Name:         "api-first",
		HostPatterns: []string{"api.", "/api/", "gateway", "graphql", "grpc", "rest"},
		PriorityAreas: []string{
			"broken object-level authorization",
			"GraphQL introspection",
			"mass assignment",
			"JWT forgery",
		},
		SystemInstruction: "This is an API-FIRST target. Prioritize: (1) BOLA/IDOR on every object ID parameter; " +
			"(2) GraphQL introspection and field-level auth; (3) mass assignment via undocumented fields; " +
			"(4) JWT algorithm confusion and weak signing keys; (5) rate limiting on authentication endpoints. " +
			"Map findings to OWASP API Security Top 10.",
	},
}

// SelectDomainProfile returns the best-matching DomainProfilePack for a target
// URL, or nil when no profile matches.
func SelectDomainProfile(targetURL string) *DomainProfilePack {
	lower := strings.ToLower(targetURL)
	for i := range domainProfilePacks {
		for _, pattern := range domainProfilePacks[i].HostPatterns {
			if strings.Contains(lower, pattern) {
				return &domainProfilePacks[i]
			}
		}
	}
	return nil
}

