package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"auto-bughunter/backend/internal/model"
)

type Client struct {
	BaseURL string
	APIKey  string
	Model   string
	// Optional larger coding-focused model for orchestration/planning calls.
	CodingBaseURL string
	CodingAPIKey  string
	CodingModel   string
	HTTP    *http.Client
}

func NewClient(baseURL, apiKey, model string) *Client {
	if baseURL == "" {
		baseURL = "https://api.openai.com/v1"
	}
	if model == "" {
		model = "gpt-4o-mini"
	}
	return &Client{
		BaseURL: strings.TrimRight(baseURL, "/"),
		APIKey:  apiKey,
		Model:   model,
		HTTP:    &http.Client{Timeout: 20 * time.Second},
	}
}

func (c *Client) ConfigureCodingModel(baseURL, apiKey, model string) {
	if c == nil {
		return
	}
	model = strings.TrimSpace(model)
	if model == "" {
		c.CodingBaseURL = ""
		c.CodingAPIKey = ""
		c.CodingModel = ""
		return
	}

	baseURL = strings.TrimSpace(baseURL)
	if baseURL == "" {
		baseURL = c.BaseURL
	}
	apiKey = strings.TrimSpace(apiKey)
	if apiKey == "" {
		apiKey = c.APIKey
	}

	c.CodingBaseURL = strings.TrimRight(baseURL, "/")
	c.CodingAPIKey = apiKey
	c.CodingModel = model
}

func (c *Client) Summarize(ctx context.Context, target string, findings []model.Finding) string {
	return c.SummarizeWithKnowledge(ctx, target, findings, nil)
}

func (c *Client) SummarizeWithKnowledge(ctx context.Context, target string, findings []model.Finding, knowledge *model.SecurityKnowledgeContext) string {
	if !c.shouldCallProvider() {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}

	payload := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{
				"role":    "system",
				"content": "You are a defensive AppSec assistant. Summarize scanner findings for authorized remediation only. Use supplied curated references as supporting context, and preserve citations as source titles plus URLs.",
			},
			{
				"role":    "user",
				"content": fmt.Sprintf("Target: %s\nFindings JSON: %s\nKnowledge Context JSON: %s\nProvide: 1) risk summary 2) top 3 priorities 3) remediation sequence 4) supporting citations when knowledge context is present.", target, mustJSON(findings), mustJSON(knowledge)),
			},
		},
		"temperature": 0.2,
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.BaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	if strings.TrimSpace(c.APIKey) != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}

	var out struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	if len(out.Choices) == 0 || strings.TrimSpace(out.Choices[0].Message.Content) == "" {
		return localReasonerSummaryWithKnowledge(target, findings, knowledge)
	}
	return out.Choices[0].Message.Content
}

func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		return "[]"
	}
	return string(b)
}

// VulnerabilityHypothesis is a single testable vulnerability hypothesis
// generated by the AI provider and intended for deterministic scanner
// verification. The scanner executes a targeted probe based on the
// category/endpoint/payload hint and only surfaces a finding when the
// oracle confirms the vulnerability.
type VulnerabilityHypothesis struct {
	ID          string `json:"id"`
	Endpoint    string `json:"endpoint"`
	Method      string `json:"method"`
	ParamName   string `json:"paramName,omitempty"`
	PayloadHint string `json:"payloadHint"`
	Category    string `json:"category"`
	Rationale   string `json:"rationale"`
}

// Hypothesize asks the configured AI provider to generate testable
// vulnerability hypotheses for the given target given the current finding
// set and known surface endpoints. Each hypothesis describes a specific
// probe (endpoint, parameter, payload) that the scanner verifies with a
// deterministic oracle. Only scanner-confirmed hypotheses are surfaced as
// findings, preventing hallucinated reports.
//
// Falls back to a rule-based local reasoner when no AI provider is configured.
func (c *Client) Hypothesize(ctx context.Context, target string, findings []model.Finding, endpoints []string) []VulnerabilityHypothesis {
	if c == nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if !c.shouldCallProvider() {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	type hypothesisRequest struct {
		Target       string          `json:"target"`
		Findings     []model.Finding `json:"findings"`
		Endpoints    []string        `json:"endpoints"`
		Instructions string          `json:"instructions"`
	}
	hreq := hypothesisRequest{
		Target:    target,
		Findings:  findings,
		Endpoints: endpoints,
		Instructions: "Generate up to 5 testable vulnerability hypotheses. For each, specify: " +
			"a concrete endpoint URL, HTTP method (GET/POST), optional parameter name, " +
			"a payload hint (e.g. \"' OR 1=1 --\", \"<script>\", \"/../etc/passwd\"), " +
			"category (one of: sqli|xss|open_redirect|ssrf|cors|auth_bypass|idor|ssti|business_logic), " +
			"and a rationale. Only propose hypotheses verifiable by a deterministic scanner oracle. " +
			"Reply with strict JSON only: " +
			"{\"hypotheses\":[{\"id\":string,\"endpoint\":string,\"method\":string,\"paramName\":string,\"payloadHint\":string,\"category\":string,\"rationale\":string}]}",
	}
	userJSON, err := json.Marshal(hreq)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	payload := map[string]any{
		"model": c.Model,
		"messages": []map[string]string{
			{
				"role":    "system",
				"content": "You are an autonomous security researcher generating testable vulnerability hypotheses. Reply with strict JSON.",
			},
			{
				"role":    "user",
				"content": string(userJSON),
			},
		},
		"temperature":     0.3,
		"response_format": map[string]string{"type": "json_object"},
	}

	body, err := json.Marshal(payload)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.BaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if strings.TrimSpace(c.APIKey) != "" {
		req.Header.Set("Authorization", "Bearer "+c.APIKey)
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.HTTP.Do(req)
	if err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	if len(apiResp.Choices) == 0 {
		return localReasonerHypotheses(target, findings, endpoints)
	}

	content := stripCodeFence(strings.TrimSpace(apiResp.Choices[0].Message.Content))
	if content == "" {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	var parsed struct {
		Hypotheses []VulnerabilityHypothesis `json:"hypotheses"`
	}
	if err := json.Unmarshal([]byte(content), &parsed); err != nil {
		return localReasonerHypotheses(target, findings, endpoints)
	}
	return parsed.Hypotheses
}

func (c *Client) shouldCallProvider() bool {
	return shouldCallProviderFor(c.BaseURL, c.APIKey)
}

func (c *Client) planningProvider() (baseURL, apiKey, model string) {
	baseURL = c.BaseURL
	apiKey = c.APIKey
	model = c.Model

	if strings.TrimSpace(c.CodingModel) == "" {
		return baseURL, apiKey, model
	}
	if shouldCallProviderFor(c.CodingBaseURL, c.CodingAPIKey) {
		return c.CodingBaseURL, c.CodingAPIKey, c.CodingModel
	}
	return baseURL, apiKey, model
}

func shouldCallProviderFor(baseURL, apiKey string) bool {
	// Keep OpenAI default behavior: require an API key.
	const defaultOpenAIBase = "https://api.openai.com/v1"
	base := strings.TrimRight(strings.ToLower(strings.TrimSpace(baseURL)), "/")
	if strings.TrimSpace(apiKey) != "" {
		return true
	}
	return base != strings.ToLower(defaultOpenAIBase)
}
