package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"auto-bughunter/backend/internal/model"
)

// OpenHackExpertAssessment is the structured response the OpenHack expert
// prompt returns for a single finding. The fields are intentionally a small
// JSON subset of the full OpenHack scenario contract — just enough to enrich
// existing findings with expert-grade reasoning, severity due diligence,
// proof obligations, and suggested follow-up probes.
type OpenHackExpertAssessment struct {
	// ExpertID is echoed by the LLM so callers can sanity-check that the
	// model honoured the requested expert family.
	ExpertID string `json:"expertId,omitempty"`
	// Decision is one of: "confirmed", "candidate", "needs_context",
	// "rejected". Mirrors the OpenHack scenario result vocabulary.
	Decision string `json:"decision"`
	// RecommendedSeverity is the expert's re-rated severity. May differ
	// from the source finding's severity.
	RecommendedSeverity string `json:"recommendedSeverity,omitempty"`
	// Confidence is the LLM's 0-1 confidence in the assessment.
	Confidence float64 `json:"confidence,omitempty"`
	// Rationale is a plain-English explanation linking the finding's
	// evidence to the OpenHack quality gate (attacker input → boundary/sink
	// → missing or uncertain guard).
	Rationale string `json:"rationale,omitempty"`
	// ProofObligations lists what still needs to be proven to promote this
	// candidate to a final finding. Empty when Decision is "confirmed" or
	// "rejected".
	ProofObligations []string `json:"proofObligations,omitempty"`
	// FollowUpProbes are short attack-step suggestions the operator can run
	// to close the open obligations. Capped at 5 by the caller.
	FollowUpProbes []string `json:"followUpProbes,omitempty"`
	// EvidenceGaps lists missing or weak evidence the LLM saw.
	EvidenceGaps []string `json:"evidenceGaps,omitempty"`
}

// OpenHackTriageDecision is the parsed finding-triage prompt output for a
// single candidate finding.
type OpenHackTriageDecision struct {
	// Decision is one of: "accepted", "downgraded", "duplicate", "rejected",
	// "needs_context" (per docs/openhack/agents/orchestration/finding-triage.md).
	Decision string `json:"decision"`
	// FinalSeverity is the triage agent's final severity rating after due
	// diligence.
	FinalSeverity string `json:"finalSeverity,omitempty"`
	// SeverityRationale justifies FinalSeverity in plain language.
	SeverityRationale string `json:"severityRationale,omitempty"`
	// Confidence is the 0-1 triage confidence.
	Confidence float64 `json:"confidence,omitempty"`
	// EvidenceAssessment summarises whether the proof is strong, weak, or
	// missing.
	EvidenceAssessment string `json:"evidenceAssessment,omitempty"`
	// EvidenceGaps lists what is still missing for an accepted decision.
	EvidenceGaps []string `json:"evidenceGaps,omitempty"`
	// RequiredChanges lists report-quality fixes the operator must make
	// before publishing the finding.
	RequiredChanges []string `json:"requiredChanges,omitempty"`
	// StandardisedTitle is the OpenHack canonical title form
	// "<severity> - <type of vuln> - <location>" when the decision allows
	// promotion to a final finding.
	StandardisedTitle string `json:"standardisedTitle,omitempty"`
}

// RunOpenHackExpert sends a single finding to the configured AI provider with
// the supplied OpenHack expert system prompt and parses the JSON response.
//
// systemPrompt is the full text generated by openhack.Pack.SystemPromptFor.
// expertID is recorded in the user payload so the LLM can echo it back.
// finding is the source finding being assessed.
//
// Returns an empty assessment (zero-value) when no AI provider is configured
// or when the model returns un-parseable output. Callers should treat an empty
// Decision as "the LLM did not produce a usable result; keep the source
// finding as-is".
//
// Routing: this method uses the planning provider (coding model) when one is
// configured because expert review benefits from the stronger reasoning
// budget; it falls back to the primary provider otherwise. This makes the
// same call site work transparently against a local Ollama deployment
// (OpenAI-compatible) and external OpenAI/Anthropic/Gemini/Bedrock models.
func (c *Client) RunOpenHackExpert(ctx context.Context, systemPrompt, expertID string, finding model.Finding) OpenHackExpertAssessment {
	if c == nil || !c.shouldCallProvider() {
		return OpenHackExpertAssessment{}
	}
	systemPrompt = strings.TrimSpace(systemPrompt)
	if systemPrompt == "" {
		return OpenHackExpertAssessment{}
	}

	userPayload := map[string]any{
		"expertId":             strings.TrimSpace(expertID),
		"finding":              compactFinding(finding),
		"outputContract":       openHackExpertSchema,
		"instructions":         openHackExpertInstructions,
	}
	if guidance := c.retrieveKnowledgeGuidance(
		ctx,
		"openhack-expert",
		openHackKnowledgeQuery("openhack-expert", finding),
		knowledgeCategoriesForFinding(finding),
		4,
		1200,
	); guidance != "" {
		userPayload["knowledgeGuidance"] = guidance
	}
	body, err := json.Marshal(userPayload)
	if err != nil {
		return OpenHackExpertAssessment{}
	}

	messages := []Message{
		{Role: "system", Content: systemPrompt + "\n\n" + openHackExpertReminder + " Use any provided knowledgeGuidance field as curated HackTricks / PayloadsAllTheThings support for severity, proof obligations, and follow-up probes."},
		{Role: "user", Content: string(body)},
	}
	content, err := c.planningComplete(ctx, messages, 0.2, true)
	if err != nil || strings.TrimSpace(content) == "" {
		return OpenHackExpertAssessment{}
	}
	var out OpenHackExpertAssessment
	if err := json.Unmarshal([]byte(content), &out); err != nil {
		return OpenHackExpertAssessment{}
	}
	out.Confidence = clamp01(out.Confidence)
	if len(out.FollowUpProbes) > 5 {
		out.FollowUpProbes = out.FollowUpProbes[:5]
	}
	if len(out.ProofObligations) > 8 {
		out.ProofObligations = out.ProofObligations[:8]
	}
	if len(out.EvidenceGaps) > 8 {
		out.EvidenceGaps = out.EvidenceGaps[:8]
	}
	out.Decision = strings.ToLower(strings.TrimSpace(out.Decision))
	out.RecommendedSeverity = strings.ToLower(strings.TrimSpace(out.RecommendedSeverity))
	return out
}

// RunOpenHackTriage runs the OpenHack finding-triage prompt over a single
// candidate finding. See RunOpenHackExpert for routing semantics — both
// methods share the same provider plumbing so the local-vs-external choice
// follows the rest of the AI client.
func (c *Client) RunOpenHackTriage(ctx context.Context, systemPrompt string, finding model.Finding) OpenHackTriageDecision {
	if c == nil || !c.shouldCallProvider() {
		return OpenHackTriageDecision{}
	}
	systemPrompt = strings.TrimSpace(systemPrompt)
	if systemPrompt == "" {
		return OpenHackTriageDecision{}
	}

	userPayload := map[string]any{
		"candidate":      compactFinding(finding),
		"outputContract": openHackTriageSchema,
		"instructions":   openHackTriageInstructions,
	}
	if guidance := c.retrieveKnowledgeGuidance(
		ctx,
		"openhack-triage",
		openHackKnowledgeQuery("openhack-triage", finding),
		knowledgeCategoriesForFinding(finding),
		4,
		1200,
	); guidance != "" {
		userPayload["knowledgeGuidance"] = guidance
	}
	body, err := json.Marshal(userPayload)
	if err != nil {
		return OpenHackTriageDecision{}
	}
	messages := []Message{
		{Role: "system", Content: systemPrompt + "\n\n" + openHackTriageReminder + " Use any provided knowledgeGuidance field as curated HackTricks / PayloadsAllTheThings support when judging evidence quality and remediation direction."},
		{Role: "user", Content: string(body)},
	}
	content, err := c.planningComplete(ctx, messages, 0.2, true)
	if err != nil || strings.TrimSpace(content) == "" {
		return OpenHackTriageDecision{}
	}
	var out OpenHackTriageDecision
	if err := json.Unmarshal([]byte(content), &out); err != nil {
		return OpenHackTriageDecision{}
	}
	out.Confidence = clamp01(out.Confidence)
	out.Decision = strings.ToLower(strings.TrimSpace(out.Decision))
	out.FinalSeverity = strings.ToLower(strings.TrimSpace(out.FinalSeverity))
	return out
}

// compactFinding builds a lightweight, JSON-friendly representation of a
// finding for the OpenHack prompt user payload. Keeping the payload narrow
// matters for local models that have small context windows.
func compactFinding(f model.Finding) map[string]any {
	out := map[string]any{
		"id":             f.ID,
		"category":       f.Category,
		"severity":       string(f.Severity),
		"title":          f.Title,
		"description":    truncateText(f.Description, 800),
		"evidence":       truncateText(f.Evidence, 1200),
		"recommendation": truncateText(f.Recommendation, 400),
		"affectedUrl":    f.AffectedURL,
		"cwe":            f.CWE,
		"confidence":     f.Confidence,
	}
	if f.AffectedParameter != "" {
		out["affectedParameter"] = f.AffectedParameter
	}
	if len(f.Sources) > 0 {
		out["sources"] = f.Sources
	}
	return out
}

func truncateText(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

func clamp01(v float64) float64 {
	if v < 0 {
		return 0
	}
	if v > 1 {
		return 1
	}
	return v
}

const openHackExpertSchema = `{"expertId":string,"decision":"confirmed|candidate|needs_context|rejected","recommendedSeverity":"critical|high|medium|low|info","confidence":number,"rationale":string,"proofObligations":[string],"followUpProbes":[string],"evidenceGaps":[string]}`

const openHackExpertInstructions = "Apply the OpenHack quality gate: state whether attacker-controlled input may reach a boundary or sink, and whether the guard is missing, uncertain, or class-specific. Use the source finding's evidence as primary input. Do not invent evidence the source finding does not contain — flag it under evidenceGaps instead."

const openHackExpertReminder = "Output strict JSON matching the requested outputContract. No prose outside the JSON. If the evidence does not justify the finding's claimed severity, downgrade it in recommendedSeverity and explain why in rationale."

const openHackTriageSchema = `{"decision":"accepted|downgraded|duplicate|rejected|needs_context","finalSeverity":"critical|high|medium|low|info","severityRationale":string,"confidence":number,"evidenceAssessment":string,"evidenceGaps":[string],"requiredChanges":[string],"standardisedTitle":string}`

const openHackTriageInstructions = "Perform OpenHack finding-triage due diligence: re-rate severity from evidence (do not accept the source severity by default), check minimum attacker role, confidentiality/integrity/availability blast radius, and report quality. Only 'accepted' and 'downgraded' decisions may produce a final finding."

const openHackTriageReminder = "Output strict JSON matching the requested outputContract. Severity must be justified plainly in severityRationale. Use 'needs_context' if the evidence is genuinely insufficient rather than guessing."

// Compile-time guard so the schema constants are referenced from at least one
// location besides the prompt construction; keeps `go vet -unusedwrite` quiet
// when the project tightens its lint rules.
var _ = fmt.Sprintf("%s%s%s%s%s%s",
	openHackExpertSchema, openHackExpertInstructions, openHackExpertReminder,
	openHackTriageSchema, openHackTriageInstructions, openHackTriageReminder,
)
