package report

import (
	"archive/zip"
	"bytes"
	"fmt"
	"regexp"
	"strings"
	"time"

	"auto-bughunter/backend/internal/model"
)

// FindingToBugBountySubmission converts a finding into the canonical
// BugBountySubmission structure, applying enrichment first so that CVSS/CWE/
// References are populated when available.
func FindingToBugBountySubmission(f model.Finding, target string) model.BugBountySubmission {
	enriched := EnrichFinding(f)
	return model.BugBountySubmission{
		Title:       enriched.Title,
		Severity:    enriched.Severity,
		CVSSVector:  enriched.CVSSVector,
		CVSSScore:   enriched.CVSSScore,
		CWE:         enriched.CWE,
		Asset:       findingAsset(enriched, target),
		Summary:     enriched.Description,
		Steps:       enriched.ReproductionSteps,
		Impact:      enriched.Impact,
		Remediation: enriched.Recommendation,
		References:  enriched.References,
	}
}

// RenderBugBountyMarkdown returns a Markdown bug-bounty submission for a
// single finding. The format follows the structure that HackerOne, Bugcrowd
// and Intigriti all accept (Summary, Steps to reproduce, Impact, Remediation,
// References).
func RenderBugBountyMarkdown(f model.Finding, target string) string {
	sub := FindingToBugBountySubmission(f, target)
	var b strings.Builder
	b.WriteString("# " + sub.Title + "\n\n")

	b.WriteString("## Summary\n\n")
	if sub.Summary != "" {
		b.WriteString(sub.Summary + "\n\n")
	} else {
		b.WriteString("_No description provided._\n\n")
	}

	b.WriteString("## Vulnerability Details\n\n")
	rows := [][2]string{
		{"Severity", sevDisplay(sub.Severity)},
		{"CWE", sub.CWE},
		{"CVSS", fmtCVSS(sub.CVSSScore, sub.CVSSVector)},
		{"Asset", sub.Asset},
	}
	if f.AffectedParameter != "" {
		rows = append(rows, [2]string{"Affected Parameter", f.AffectedParameter})
	}
	for _, row := range rows {
		if strings.TrimSpace(row[1]) != "" {
			b.WriteString(fmt.Sprintf("- **%s:** %s\n", row[0], row[1]))
		}
	}
	b.WriteString("\n")

	b.WriteString("## Steps to Reproduce\n\n")
	if len(sub.Steps) == 0 {
		b.WriteString("_No reproduction steps recorded for this finding._\n\n")
	} else {
		for i, step := range sub.Steps {
			b.WriteString(fmt.Sprintf("%d. %s\n", i+1, step))
		}
		b.WriteString("\n")
	}

	if f.Evidence != "" {
		b.WriteString("## Evidence\n\n```\n" + f.Evidence + "\n```\n\n")
	}
	if curl := strings.TrimSpace(f.EvidenceFields["curlReproducer"]); curl != "" {
		b.WriteString("## Reproducer\n\n```bash\n" + curl + "\n```\n\n")
	} else if f.PoC != "" {
		b.WriteString("## Proof of Concept\n\n```\n" + f.PoC + "\n```\n\n")
	}

	b.WriteString("## Impact\n\n")
	if sub.Impact != "" {
		b.WriteString(sub.Impact + "\n\n")
	} else {
		b.WriteString("_Impact assessment not available._\n\n")
	}

	b.WriteString("## Suggested Remediation\n\n")
	if sub.Remediation != "" {
		b.WriteString(sub.Remediation + "\n\n")
	} else {
		b.WriteString("_No remediation guidance recorded._\n\n")
	}

	if len(sub.References) > 0 {
		b.WriteString("## References\n\n")
		for _, r := range sub.References {
			b.WriteString("- " + r + "\n")
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("_Generated by Auto Bughunter at " + time.Now().UTC().Format(time.RFC3339) + "_\n")
	return b.String()
}

var safeFilenameRe = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

// safeFilename produces a filesystem-safe filename component from an
// arbitrary string by replacing all non-alphanumeric characters with `-` and
// trimming leading/trailing separators.
func safeFilename(s string) string {
	if s == "" {
		return "finding"
	}
	cleaned := safeFilenameRe.ReplaceAllString(s, "-")
	cleaned = strings.Trim(cleaned, "-_.")
	if cleaned == "" {
		return "finding"
	}
	if len(cleaned) > 80 {
		cleaned = cleaned[:80]
	}
	return cleaned
}

// RenderBugBountyZip produces a zip archive containing one Markdown
// submission file per finding plus a top-level `INDEX.md` summary.
func RenderBugBountyZip(job *model.ScanJob) ([]byte, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	target := ""
	if job != nil {
		target = job.Target
	}

	var index strings.Builder
	index.WriteString("# Bug Bounty Submission Bundle\n\n")
	if job != nil {
		index.WriteString("**Target:** " + job.Target + "  \n")
		index.WriteString("**Scan ID:** " + job.ID + "  \n")
		index.WriteString("\n")
	}
	index.WriteString("| # | Severity | Title | File |\n|---|----------|-------|------|\n")

	if job != nil {
		for i, f := range job.Findings {
			fname := fmt.Sprintf("%02d-%s-%s.md", i+1, strings.ToLower(string(f.Severity)), safeFilename(f.ID))
			content := RenderBugBountyMarkdown(f, target)
			fileWriter, err := zw.Create(fname)
			if err != nil {
				return nil, err
			}
			if _, err := fileWriter.Write([]byte(content)); err != nil {
				return nil, err
			}
			index.WriteString(fmt.Sprintf("| %d | %s | %s | %s |\n", i+1, sevDisplay(f.Severity), f.Title, fname))
		}
	}

	idxWriter, err := zw.Create("INDEX.md")
	if err != nil {
		return nil, err
	}
	if _, err := idxWriter.Write([]byte(index.String())); err != nil {
		return nil, err
	}
	if err := zw.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
